// Writes `dist/client/fonts.js`: registers Geist and Geist Mono (latin, latin-ext)
// on `document.fonts`, from data URIs.
// - discovery.js bundles CSS with esbuild without a loader for `.woff2`,
//   and a report must work offline as a single file, so the fonts are inlined
// - the UI lives in a shadow root, which ignores its own `@font-face` rules,
//   but uses the fonts of the document
import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

const require = createRequire(import.meta.url);
const FONTS = {
  "@fontsource-variable/geist": "Geist",
  "@fontsource-variable/geist-mono": "Geist Mono",
};
const SUBSETS = ["latin", "latin-ext"];

const faces = Object.entries(FONTS).flatMap(([pkg, family]) => {
  const dir = path.dirname(require.resolve(`${pkg}/package.json`));
  const source = fs.readFileSync(path.join(dir, "index.css"), "utf8");
  return [...source.matchAll(/\/\* ([\w-]+) \*\/\s*@font-face \{([^}]+)\}/g)]
    .filter(([, name]) =>
      SUBSETS.some((subset) => name.endsWith(`-${subset}-wght-normal`)),
    )
    .map(([, , rule]) => {
      const file = rule.match(/url\(\.\/(files\/[^)]+)\)/)[1];
      const data = fs.readFileSync(path.join(dir, file)).toString("base64");
      return {
        family,
        src: `url(data:font/woff2;base64,${data}) format("woff2")`,
        descriptors: {
          weight: rule.match(/font-weight: ([^;]+);/)[1],
          display: "swap",
          unicodeRange: rule.match(/unicode-range: ([^;]+);/)[1],
        },
      };
    });
});

const out = path.resolve(import.meta.dirname, "../dist/client/fonts.js");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  `// Generated by scripts/fonts.mjs
for (const { family, src, descriptors } of ${JSON.stringify(faces)}) {
  document.fonts.add(new FontFace(family, src, descriptors));
}
`,
);
