import {
  getCopyToClipboardButton,
  getModulesTree,
  getTreeModule,
} from "./_common";

function getMetroWarn({
  when,
  href,
  linkText,
  content,
}: {
  when: string;
  href?: string;
  linkText?: string;
  content: (DiscoveryViewConfig | string)[];
}) {
  return {
    view: "alert-warning",
    when,
    className: "m-v-8",
    content: [
      ...content,
      linkText && href
        ? {
            view: "link",
            data: {
              external: true,
              href,
              text: linkText,
            },
          }
        : null,
    ].filter(Boolean),
  };
}

discovery.page.define("module", {
  view: "context",
  data: `{
    $currentModule: $.modules.[path = #.id].pick(0); 
    ...$, 
    currentModule: $currentModule,
    overview: $.moduleOverview(#.id),
    isEntry: $currentModule.isEntry,
    isInjectedByMetro: $currentModule.path = '__prelude__' or $currentModule.path has '@react-native/js-polyfills',
    isWebpackRuntime: $currentModule.path has '__runtime__',
  }`,
  content: [
    {
      view: "block",
      className: "mo-wrap",
      content: [
        { view: "module-overview", data: "overview" },
        getCopyToClipboardButton({
          textToCopy: `$.currentModule.path`,
          className: "mo-copy",
        }),
      ],
    },

    {
      view: "tabs",
      name: "tabs",
      // value: "networkGraph", //FIXME
      className: "mo-tabs",
      tabs: [
        {
          value: "mcontent",
          text: "Code",
        },
        {
          value: "mimports",
          when: "overview.imports",
          content: ["text:'Imports '", "pill-badge: overview.imports.size()"],
        },
        {
          value: "networkGraph",
          when: "not isInjectedByMetro and not isEntry and not isWebpackRuntime",
          content: ["text:'Imported by '", "pill-badge: overview.importedBy"],
        },
        {
          value: "mduplicates",
          when: "not isInjectedByMetro and not isEntry and not isWebpackRuntime and currentModule.duplicates",
          content: ["text:'Duplicates '", "pill-badge: overview.duplicates"],
        },
      ],
      content: {
        view: "switch",
        content: [
          {
            when: '#.tabs="mcontent"',
            content: [
              getMetroWarn({
                when: "$.currentModule.path = '__prelude__'",
                content: [
                  "html: '<b>__prelude__</b>'",
                  "text: ' is a special runtime code that was generated by the Metro bundler, see: '",
                ],
                href: "https://github.com/facebook/metro/blob/f595e9e1c9021ad372b489be8958cc298eb1e0d9/packages/metro/src/lib/getPreludeCode.js#L25-L33",
                linkText: "getPreludeCode.js",
              }),
              getMetroWarn({
                when: "$.currentModule.path = '__runtime__'",
                content: [
                  "html: '<b>__runtime__</b>'",
                  "text: ' is a special runtime code that was generated by the Webpack/Rspack bundler'",
                ],
              }),
              getMetroWarn({
                when: "$.currentModule.path has '@react-native/js-polyfills'",
                content: [
                  "html: '<b>@react-native/js-polyfills/*</b>'",
                  "text: ' is a special package that was injected by the Metro bundler, see: '",
                ],
                href: "https://github.com/facebook/react-native/blob/198c6fc81cda67a46fff457cc39eb2a297eddc01/packages/metro-config/src/index.flow.js#L61",
                linkText: "rn/metro-config/index.js",
              }),
              getMetroWarn({
                when: "$.currentModule.path has 'metro-runtime'",
                content: [
                  "html: '<b>metro-runtime/*</b>'",
                  "text: ' is a special package that was injected by the Metro bundler, see: '",
                ],
                href: "https://github.com/facebook/metro/blob/f595e9e1c9021ad372b489be8958cc298eb1e0d9/packages/metro-config/src/defaults/defaults.js#L61-L63",
                linkText: "metro-config/index.js",
              }),
              {
                view: "hstack",
                className: "flex-no-wrap",
                content: [
                  {
                    view: "block",
                    className: "width-50p",
                    content: [
                      {
                        view: "h5",
                        className: "mo-pane-title",
                        content: [
                          "text: 'Source'",
                          "text: ' · ' + overview.sourceLines.pluralWithCount(['line', 'lines']) + ' · ' + overview.sourceSize.formatBytes()",
                        ],
                      },
                      {
                        view: "source",
                        syntax: "ts",
                        source: "=$.currentModule.source.code",
                      },
                    ],
                  },
                  {
                    view: "block",
                    className: "width-50p",
                    content: [
                      {
                        view: "h5",
                        className: "mo-pane-title",
                        content: [
                          "text: 'Output'",
                          "text: ' · ' + overview.outputLines.pluralWithCount(['line', 'lines']) + ' · ' + overview.outputSize.formatBytes()",
                        ],
                      },
                      {
                        view: "context",
                        modifiers: [
                          {
                            view: "checkbox",
                            name: "prettify",
                            checked: true,
                            className: "prettify-checkbox",
                            content: 'text:"Prettify"',
                          },
                        ],
                        content: [
                          {
                            view: "source-prettify",
                            syntax: "ts",
                            source:
                              "=(#.prettify ? $.currentModule.output.code.prettifyJS() : $.currentModule.output.code)",
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            when: '#.tabs="mimports"',
            content: {
              view: "content-filter",
              data: "overview.imports",
              name: "filterByPathStr",
              content: {
                view: "list",
                data: ".[name ~= #.filterByPathStr or specifier ~= #.filterByPathStr]",
                emptyText: "This module doesn't import anything",
                item: {
                  view: "block",
                  className: "mo-import",
                  content: [
                    {
                      view: "text-match",
                      className: "mo-import-specifier",
                      data: "{ text: specifier, match: #.filterByPathStr }",
                    },
                    "html: '<span class=\"mo-arrow\">→</span>'",
                    {
                      view: "switch",
                      content: [
                        {
                          when: "missing",
                          content: [
                            "text: name",
                            "badge: { text: 'not in bundle', color: 'rgba(128,128,128,.25)' }",
                          ],
                        },
                        { content: getTreeModule({ hasTextMatch: true }) },
                      ],
                    },
                  ],
                },
              },
            },
          },
          {
            when: '#.tabs="networkGraph"',
            content: {
              view: "context",
              context: `{ ...#, maxParentDepth: $.currentModule.getBestNetworkGraphSize() }`,
              modifiers: [
                "html: '<br/>'",
                "text:'Max parent depth: '",
                {
                  view: "input",
                  name: "maxParentDepth",
                  className: "inline-block",
                  htmlType: "number",
                  htmlMin: 1,
                  htmlMax: 10,
                },
              ],
              content: [
                {
                  view: "context",
                  data: `{
                    // Vars
                    $tmp: $.currentModule.getNetworkGraph({ maxParentDepth: #.maxParentDepth });
                    $limit: 150;
                    // Return data
                    currentModule: $.currentModule,                      
                    entryPointPath: $tmp.entryPointPath,
                    limit: $limit,
                    data: $tmp.data,
                    graph: { nodes: $tmp.nodes, links: $tmp.links },
                    isGraphTooBig: $tmp.data.size() > $limit,
                  }`,
                  content: [
                    // TODO use for debugging
                    // {
                    //   view: "struct",
                    //   expanded: 2,
                    // },
                    {
                      when: "isGraphTooBig",
                      view: "block",
                      className: "m-v-8",
                      content: [
                        {
                          view: "alert-warning",
                          data: '"Amount of dependencies "+$.data.size()+" (limit: "+$.limit+") are too big to display as a graph :("',
                        },
                      ],
                    },
                    {
                      view: "hstack",
                      className: "flex-no-wrap two-column",
                      content: [
                        {
                          when: "not isGraphTooBig",
                          view: "import-graph",
                          className: "ig",
                          data: "graph",
                        },

                        {
                          view: "block",
                          content: [
                            "h4: 'Modules that import this file: ' + $.currentModule.path",
                            {
                              view: "list",
                              data: `
                                $totalSize: modules.sum(=>output.sizeInBytes);
                                $toModule: => {
                                  $deepIdx: $$ + 1;
                                  ext:  $.path.getFileExtension(),
                                  name: $.path,
                                  size: $.output.sizeInBytes.formatBytes(),
                                  percent: ($.output.sizeInBytes / $totalSize).percent(3),
                                  children: $deepIdx < 2 ? $.dependents.map(=> $.$toModule()) : null,
                                };
                                $.currentModule.dependents.map(=> $.$toModule(0))
                              `,
                              emptyText: "⚠️ No importing modules found",
                              item: {
                                view: "tree",
                                expanded: false,
                                itemConfig: {
                                  content: getTreeModule({
                                    hasTextMatch: true,
                                  }),
                                  children: `$.children`,
                                },
                              },
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          },
          {
            when: '#.tabs="mduplicates"',
            content: getModulesTree({
              data: `
              $totalSize: modules.sum(=>output.sizeInBytes);
              $toModule: => {
                ext:  $.path.getFileExtension(),
                name: $.path, 
                size: $.output.sizeInBytes.formatBytes(), 
                percent: ($.output.sizeInBytes / $totalSize).percent(3),
              };
              currentModule.duplicates.map(=> $.$toModule())
            `,
            }),
          },
        ],
      },
    },
  ],
});
