import path from "node:path";

// Paths are relative to `dist/`, where this file is emitted
const config = {
  name: "react-native-bundle-discovery",
  // Used by `yarn dev` only: loads `<repo root>/tmp/metro-stats.json`
  // (and compares it with the `COMPARE=<path>` report when the env var is set)
  data: () => {
    const { withComparison, withRecommendations } = require(
      path.resolve(__dirname, "rsdoctor.js"),
    );
    const report = withRecommendations(
      require(path.resolve(__dirname, "../../../tmp/metro-stats.json")),
    );
    const before = process.env.COMPARE && path.resolve(process.env.COMPARE);
    return before ? withComparison(report, require(before), before) : report;
  },
  setup: path.resolve(__dirname, "client/setup.js"),
  view: {
    assets: [
      // Fonts (generated by `scripts/fonts.mjs`) and global styles
      path.resolve(__dirname, "client/fonts.js"),
      path.resolve(__dirname, "../assets/global.css"),
      // Pages
      path.resolve(__dirname, "client/pages/default.js"),
      path.resolve(__dirname, "client/pages/module.js"),
      path.resolve(__dirname, "client/pages/moduleDiff.js"),
      path.resolve(__dirname, "client/pages/package.js"),
      // Custom views
      path.resolve(__dirname, "client/views/prettify.js"),
      path.resolve(__dirname, "client/views/importGraph.js"),
      path.resolve(__dirname, "client/views/moduleOverview.js"),
      path.resolve(__dirname, "client/views/packageOverview.js"),
      path.resolve(__dirname, "client/views/insights.js"),
      path.resolve(__dirname, "client/views/compare.js"),
      path.resolve(__dirname, "client/views/codeDiff.js"),
      path.resolve(__dirname, "client/views/reportBar.js"),
      path.resolve(__dirname, "client/views/treemap.js"),
      path.resolve(__dirname, "client/views/persistedFilterInput.js"),
    ],
  },
};

export default config;
