import { existsSync, readFileSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";
import chalk from "chalk";
import type {
  BundleReport,
  ReportModule,
  ReportModuleDependency,
  ReportPackage,
} from "./types";

// Minimal subset of the esbuild metafile (https://esbuild.github.io/api/#metafile)
interface EsbuildImport {
  path: string;
  kind: string;
  external?: boolean;
  original?: string;
}

interface EsbuildInput {
  bytes: number;
  imports: EsbuildImport[];
}

interface EsbuildOutput {
  bytes: number;
  entryPoint?: string;
  inputs: Record<string, { bytesInOutput: number }>;
}

export interface EsbuildMetafile {
  inputs: Record<string, EsbuildInput>;
  outputs: Record<string, EsbuildOutput>;
}

// Virtual entry generated by `@rnx-kit/metro-serializer-esbuild` (imports polyfills + the real entry point)
const RNX_PRELUDE = "virtual:metro:__rnx_prelude__";
const packageRegex = /(?:^|\/)node_modules\/((?:@[^/]+\/)?[^/]+)/g;

export const isEsbuildMetafile = (
  // biome-ignore lint/suspicious/noExplicitAny: arbitrary JSON input
  reportJson: any,
  reportPath: string,
  noLogs?: boolean,
): boolean => {
  try {
    if (
      reportJson?.inputs &&
      typeof reportJson.inputs === "object" &&
      reportJson?.outputs &&
      typeof reportJson.outputs === "object" &&
      !Array.isArray(reportJson?.modules)
    ) {
      !noLogs &&
        console.info(
          `Detected ${chalk.red("esbuild metafile")} format in the input file: ${chalk.green(reportPath)}`,
        );
      return true;
    }
    return false;
  } catch {
    return false;
  }
};

export const isEsbuildMetafilePath = (reportPath: string): boolean => {
  try {
    const reportJson = require(reportPath);
    return isEsbuildMetafile(reportJson, reportPath, true);
  } catch {
    return false;
  }
};

// Files from non-`file` namespaces are formatted as `<namespace>:<path>`
const isVirtual = (inputPath: string): boolean =>
  !isAbsolute(inputPath) && /^[\w-]+:/.test(inputPath);

/**
 * Metafile paths are relative to esbuild's working directory, which is not stored in the file.
 * Try the metafile folder (and its parents) and then `process.cwd()`; pick the first one where the inputs exist.
 */
const getRootFolder = (
  metafile: EsbuildMetafile,
  reportPath: string,
): string => {
  const probe = Object.keys(metafile.inputs).find((p) => !isVirtual(p));
  const candidates: string[] = [];
  let dir = dirname(reportPath);
  while (!candidates.includes(dir)) {
    candidates.push(dir);
    dir = dirname(dir);
  }
  candidates.push(process.cwd());

  return (
    (probe && candidates.find((root) => existsSync(resolve(root, probe)))) ||
    dirname(reportPath)
  );
};

const getPlatform = (paths: string[]): string => {
  const count = (platform: string) =>
    paths.filter((p) => new RegExp(`\\.${platform}\\.[cm]?[jt]sx?$`).test(p))
      .length;
  return count("android") > count("ios") ? "android" : "ios";
};

const getPackages = (modulePaths: string[]): ReportPackage[] => {
  const packages = new Map<string, ReportPackage>();
  for (const filePath of modulePaths) {
    // Find the LAST `node_modules/<pkg>` segment in the path
    const lastMatch = [...filePath.matchAll(packageRegex)].pop();
    if (!lastMatch) continue;

    const name = lastMatch[1];
    const end = filePath.indexOf(name, lastMatch.index) + name.length;
    const absolutePath = filePath.slice(0, end);
    if (packages.has(absolutePath)) continue;

    let version = "";
    try {
      version = JSON.parse(
        readFileSync(resolve(absolutePath, "package.json"), "utf8"),
      ).version;
    } catch {
      // `node_modules` is not available (e.g. the report was moved to another machine)
    }
    packages.set(absolutePath, { name, absolutePath, version });
  }
  return Array.from(packages.values()).sort((a, b) =>
    a.name.localeCompare(b.name),
  );
};

/**
 * Converts an esbuild metafile (e.g. written by `@rnx-kit/metro-serializer-esbuild` with the `metafile` option)
 * to the `metro-stats.json` format.
 *
 * Output sizes are `bytesInOutput` (after tree shaking and minification); modules removed by tree shaking are omitted.
 * Code is not included: esbuild hoists all modules into a single scope.
 */
export const transformEsbuildMetafile = (
  metafile: EsbuildMetafile,
  reportPath: string,
): BundleReport => {
  const rootFolder = getRootFolder(metafile, reportPath);
  const toAbsolute = (p: string) => (isVirtual(p) ? p : resolve(rootFolder, p));

  const outputs = Object.entries(metafile.outputs).filter(
    ([outputPath]) => !outputPath.endsWith(".map"),
  );
  const bytesInOutput = new Map<string, number>();
  for (const [, output] of outputs) {
    for (const [inputPath, { bytesInOutput: bytes }] of Object.entries(
      output.inputs,
    )) {
      bytesInOutput.set(inputPath, (bytesInOutput.get(inputPath) ?? 0) + bytes);
    }
  }

  const bundledInputs = Object.keys(metafile.inputs).filter(
    (p) => (bytesInOutput.get(p) ?? 0) > 0,
  );
  const bundled = new Set(bundledInputs);

  let entryPoint = outputs.find(([, o]) => o.entryPoint)?.[1].entryPoint ?? "";
  if (entryPoint === RNX_PRELUDE) {
    // The prelude imports polyfills first and the real entry point last
    entryPoint = metafile.inputs[RNX_PRELUDE]?.imports.at(-1)?.path ?? "";
  }

  const modules: ReportModule[] = bundledInputs.map((inputPath) => {
    const input = metafile.inputs[inputPath];
    return {
      path: toAbsolute(inputPath),
      source: {
        code: "", // no code in esbuild metafile
        lineCount: 0,
        sizeInBytes: input.bytes,
      },
      output: {
        code: "",
        lineCount: 0,
        sizeInBytes: bytesInOutput.get(inputPath) ?? 0,
      },
      dependencies: input.imports
        .filter((imp) => !imp.external && bundled.has(imp.path))
        .map(
          (imp): ReportModuleDependency => ({
            absolutePath: toAbsolute(imp.path),
            name: imp.original ?? imp.path,
          }),
        ),
    };
  });

  return {
    date: Date.now(), // no info in esbuild metafile
    entryPoint: entryPoint ? toAbsolute(entryPoint) : "",
    rootFolder,
    transformOptions: {
      dev: false,
      minify: true,
      platform: getPlatform(bundledInputs),
    },
    packages: getPackages(modules.map((m) => m.path)),
    modules,
  };
};
